const path = require('path')
const Koa = require('koa')
const app = new Koa()
const bodyParser = require('koa-bodyparser')
const koaStatic = require('koa-static')
const router = require('./router')
const { open ,error} = require('./lib/db/connect')
console.log('_________',path.join(__dirname,'uploads'))
app.use(koaStatic(path.join(__dirname,'uploads')))
app.use(bodyParser())
 app.use(router.routes())
app.use(router.allowedMethods())
open()
error()
app.listen(4001,()=>{
  console.log('app is listening 4001,http://127.0.0.1:4001')
})